### ISSUE TITLE
Processor does not attempt to reprocess incomplete sequences

### ISSUE THREAD

**Issue by shunt16** [HYPERNETS/hypernets_processor#115]

**Comment by clemgoyens** [comment]
Check how to solve particular cases such as:
1. Process stopped in middle of sequence processing. When restart, make sure it reprocess the "half" processed data
2. restart processor and ask for processing end-level (e.g., L1C or L2A) but avoid that the processor looks back to all sequences that already showed an anomaly to reach the processing level

**Comment by shunt16** [comment]
Write an anomaly at the start of processing of each sequence for incomplete processing, then remove this after completion or error.

**Comment by clemgoyens** [comment]
Check if solved!!
