### ISSUE TITLE
Ad-hoc processing fails with TypeError

### ISSUE THREAD

**Issue by jkuusk** [HYPERNETS/hypernets_processor#139]
I'm running the latest hypernets_tools (main) and hypernets_processor (master, installed with pip3 install -e) from github.

Tried ad-hoc processing. At first it failed with error
No SN for hypstar instrument!

Added sn_hypstar to the metadata file of the sequence. 

Now it fails with the following error.

$: hypernets_sequence_processor -i SEQ20210511T110003 -o /tmp/sp3 -n water
Processing sequence: /home/joel/HYPSTAR1/home/joel/github/hypernets_tools_main/DATA/SEQ20210511T110003
Reading raw data...
Processing Anomalies: ['x']
Failed: TypeError("unsupported operand type(s) for ** or pow(): 'int' and 'NoneType'",)

**Comment by clemgoyens** [comment]
Hi Joel, 
Can you send me (via email?) your sequence so I can try to reproduce the error? 
Thanks!
Clémence

**Comment by clemgoyens** [comment]
Hi Joel, 
I was able to reproduce your error and to solve it by adding "lat=0000" and "lon=000" in your "metadata.txt". I will add a more explicit error message!! In the past we added default lat and lon values within the default config file in hypernets_processor but I prefer to have it from the GPS or if failing from the metadata database (which will take lat and lon based on site id - not yet implemented - I will add it on the todo list). 
But with the latest hypernets_tools/config_hypernets.ini.template, the following should be added in your metadata.txt with each sequence:
[metadata]
principal_investigator = Investigator Name
datetime = {datetime}
site_id = A Site ID
latitude = ${GPS:latitude}
longitude = ${GPS:longitude}
protocol_file_name = ${general:sequence_file}

Hope this helps! Let me know if not!
Clémence

**Comment by jkuusk** [comment]
I added lat=0000 and lon=000 tp the metadata.txt and now it fails with the following error:
Processing sequence: /home/joel/HYPSTAR1/home/joel/github/hypernets_tools_main/DATA/SEQ20210511T110003
Reading raw data...
Processing Anomalies: ['x']
Failed: IndexError('index 9 is out of bounds for axis 0 with size 9',)

**Comment by clemgoyens** [comment]
OK that is interesting. 
Can you try with more realistic coordinates? e.g.,
Lat= 43.69886
Lon= 7.30720

**Comment by jkuusk** [comment]
Still the same error

**Comment by clemgoyens** [comment]
I was able to reproduce your error with "-n water" while it should be land. Can you check: 
 hypernets_sequence_processor -i /TestSiteOperations/Toravere/SEQ20210511T110003 -o ../Test_sequences/ -ml L2A -n land --no-unc

**Comment by jkuusk** [comment]
It completes without error if I run it with -n land or without -n command line parameter.
