### ISSUE TITLE
Failed: UnboundLocalError

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_processor#140]
When I am trying to process some sequences, I am getting this error:

```
No SN for hypstar instrument!                                                           
Processing Anomalies: ['x']                                                              
Failed: UnboundLocalError("local variable 'instrument_id' referenced before assignment")

```

I am attaching one of the sequence here :
[SEQ20210626T100046.zip](https://github.com/HYPERNETS/hypernets_processor/files/6741507/SEQ20210626T100046.zip)

Any suggestion to fix it?

**Comment by javierconcha** [comment]
Do you have the "sn_hypstar" parameter in your config file?

**Comment by saberioon** [comment]
No , I don't and I never thought it should be there

**Comment by clemgoyens** [comment]
Hi Mehdi,
If you want I can provide you a script to add the serial number of your hypstar in the metadata. But indeed, when configuring the instrument you should add the SN of the instrument otherwise the processor is not able the check for the appropriate calibration files.

**Comment by saberioon** [comment]
> Hi Mehdi,
> If you want I can provide you a script to add the serial number of your hypstar in the metadata. But indeed, when configuring the instrument you should add the SN of the instrument otherwise the processor is not able the check for the appropriate calibration files.

Hi Clemence, 

I appreciate it if you send me the script, but I wonder where this code should be added? 
Why it is not listed in the config file?
Does it cross-check it with any database?

**Comment by clemgoyens** [comment]
Yes indeed, it should be in here: https://github.com/HYPERNETS/hypernets_tools/blob/main/config_hypernets.ini.template
But I still can't see it there! @corizzi any idea why?

**Comment by clemgoyens** [comment]
This should work:
#!/bin/bash
for file in $(find BSBE/03/SEQ20210311T08*/metadata.txt); do
  echo Processing $file
  if grep -F "[Metadata]" $file
  then
      # code if found
      echo Metadata header already found in $file 
  else
      # code if not found
	cat example_of_header.txt $file > $file.modified
	mv $file.modified $file
  fi
  if grep -F -e 'hypstar_sn' -e 'sn_hypstar' $file
  then 
  	echo SN instrument already in $file
  else
  	sed -i.bak "/^datetime/a $(grep "hypstar_sn" example_of_header.txt)" $file
  fi
done

#########

And in example header you should have something like this:
[Metadata]
principal_investigator = RBINS
datetime = 20210309T093159
hypstar_sn = 120241
site_id = BSBE
latitude = 50.98857
longitude = 2.835213
protocol_file_name = hypernets/resources/sequences_samples/sequence_water_1_STD.csv

**Comment by corizzi** [comment]
> Yes indeed, it should be in here: https://github.com/HYPERNETS/hypernets_tools/blob/main/config_hypernets.ini.template
> But I still can't see it there! @corizzi any idea why?

Hi Clém, 
It still has to be filled by hand in the current version. I added the placeholder in the template as a reminder : 
https://github.com/HYPERNETS/hypernets_tools/commit/887bdef14c3de095f3823a62ef49320b016ea940

**Comment by clemgoyens** [comment]
This issue is similar to issue #122. See #122 for further solutions!
