### ISSUE TITLE
calibration file does not exist

### ISSUE THREAD

**Issue by saberioon** [HYPERNETS/hypernets_processor#143]
when I run the sequence processor, I got this error 

```
Reading raw data...
No SN set for hypstar instrument! using hypstar_cal_number from config file instead.
Processing Anomalies: ['x']
Failed: OSError('/Users/mms/opt/miniconda3/lib/python3.8/site-packages/hypernets_processor/calibration/calibration_files/HYPSTAR_cal/hypstar_220241/HYPERNETS_CAL_HYPSTAR_220241_RAD_v0.1.nc calibration file does not exist')`
```

Any advice to fix it ?

**Comment by clemgoyens** [comment]
Hi Mehdi, Can you check the SN of your instrument and which Serial Number you added in your config file (hypernets tools, config_hypernets.ini) ? If the config file is properly set you should have headers in your metadata similar to: 
[Metadata]
principal_investigator = RBINS
hypstar_sn = 120241
site_id = BSBE
latitude = 50.98857
longitude = 2.835213
protocol_file_name = hypernets/resources/sequences_samples/sequence_water_1_STD.csv

with the proper hypstar_sn. 

Thanks
Clémence

**Comment by jkuusk** [comment]
220241 is correct S/N of the GFZ instrument. For some reason the config files have not been installed to /Users/mms/opt/miniconda3/lib/python3.8/site-packages/hypernets_processor/calibration/calibration_files/HYPSTAR_cal/ folder. They are available in github https://github.com/HYPERNETS/hypernets_processor/tree/master/hypernets_processor/calibration/calibration_files/HYPSTAR_cal
