### ISSUE TITLE
Update metadata for writer

### ISSUE THREAD

**Issue by shunt16** [HYPERNETS/hypernets_processor#15]

**Comment by clemgoyens** [comment]
Hey Sam, I will work on this next week! Documentation is almost done, will be easy to copy paste it after in metadata.py... so leave this to me hey!!!!

**Comment by shunt16** [comment]
Think we have all the sections now, may just need updating based on comments etc. Okay to close?

**Comment by clemgoyens** [comment]
Thanks Sam, you did my job 😉

Sorry didn't reply earlier but was at the office to prepare a potential field work (not sure why Kevin believes it will happen ...). Have to work on this tomorrow morning too but in the afternoon I have time again to work on the Hypernets processor. Should I create the empty netcdf for each level?

________________________________

**Comment by shunt16** [comment]
No problem 😊

Yeah making empty netcdf files would be good, you can start from examples/create_sample_file.py which already has it L2a and add in the others.

Enjoy the outside! (if you manage to get there 😉)
