### ISSUE TITLE
Define quality flag meanings

### ISSUE THREAD

**Issue by shunt16** [HYPERNETS/hypernets_processor#19]

**Comment by shunt16** [comment]
Value should go in [flags.py]`https://github.com/HYPERNETS/hypernets_processor/blob/master/hypernets_processor/data_io/flags.py` file

**Comment by pdevis** [comment]
I guess to some extend this needs to be done together with a discussion on the different checks we want to do on the scans before accepting them in the average or masking them. 
Do we want the quality flags of the scans to indicate why we are masking them, or only that they have been masked?
Also do we need different quality flags for different processing levels (e.g. if one of the scans has a quality flag indicating it was masked in a certain way, does this affect the quality flag of the series when they are averages, or do we only give the series a quality flag if e.g. more than 3 scans were masked, ...).
