### ISSUE TITLE
Update metadata while creating files

### ISSUE THREAD

**Issue by clemgoyens** [HYPERNETS/hypernets_processor#36]
Currently metadata comes from metadata.py. Need to be updated according to raw data, metadata and config file

**Comment by shunt16** [comment]
As you say, in terms of sources of metadata I think we have 3 sources:
(1) Metadata database we have to query
(2) The run config files
(3) Information in the raw data files

I think the steps for doing this are:
(i) Get the info from (1) and (2) before reading the raw data
(ii) Get the info from (3) in your reader
(iii) Your reader hands (1), (2) and (3) to the hypernets_dsbuilder which adds the metadata to the dataset

So I can look at (i) and (iii), while you look at (ii)?

**Comment by shunt16** [comment]
Created a separate issue (#39) for (1) above

**Comment by clemgoyens** [comment]
OK I handle (ii)!
Still missing:
- acquisition time
- acceleration -> convert to tilt?

**Comment by shunt16** [comment]
Implementation set up to do this now, by HypernetsDSBuilder querying metadata database when creating template. Waiting for creation of metadata databases (#39) for completion.
