### ISSUE TITLE
Make config files for data processing

### ISSUE THREAD

**Issue by clemgoyens** [HYPERNETS/hypernets_processor#37]
Process data with config file - including default config file (e.g., when processing quickly without the need to give extra info about site and other)

**Comment by shunt16** [comment]
As we discussed today - I've also started taking a look at defining this files in [etc](https://github.com/HYPERNETS/hypernets_processor/tree/master/hypernets_processor/etc) subpackage. These files are read at run time by the [command line interface](https://github.com/HYPERNETS/hypernets_processor/tree/master/hypernets_processor/cli) and parsed by [context](https://github.com/HYPERNETS/hypernets_processor/blob/master/hypernets_processor/context.py). In your own code you should only have to interface with the context.

I've defined three levels of config files:

- scheduler.config - that defines the schedule of what it automatically runs (kept in etc)
- processor.config - that defines processor config information, like archive directory, and defaults (kept in etc)
- job.config - that defines per job settings (local to the user, location sorted in etc/job.txt)

@clemgoyens and @pdevis - please let me know what config parameters you need (and what their defaults should be, if necessary)

**Comment by shunt16** [comment]
Solution now found, regularly updated as new config requirements added
