### ISSUE TITLE
Update variable format definition

### ISSUE THREAD

**Issue by clemgoyens** [HYPERNETS/hypernets_processor#38]

**Comment by shunt16** [comment]
Should we widen this to all file formats and add it to the v0.1 format?

**Comment by clemgoyens** [comment]
Yes indeed! Encoding and variable definition need to be reviewed for all file formats. Therefore, data ranges need to be known.

**Comment by shunt16** [comment]
Separated defining encoding to different issue #52

**Comment by clemgoyens** [comment]
Almost done. Just waiting if we need to add uncertainty budget to variables from LUT (e.i. epsilon and fresnel_coefficient)
