### ISSUE TITLE
Add suitable file encoding to variable definitions

### ISSUE THREAD

**Issue by shunt16** [HYPERNETS/hypernets_processor#52]

**Comment by clemgoyens** [comment]
Current encoding does not work for angles:
e.g., for sun zenith angle encoding is the following: 
                                                  "encoding": {'dtype': np.uint16, "scale_factor": 0.0001,
                                                               "offset": 0.0}},
gives as output:
array([1.3695, 1.3695, 1.3695, 1.6474, 1.6474, 1.6474], dtype=float32)
