### ISSUE TITLE
Add detection and separate handling for standard and non-standard sequences

### ISSUE THREAD

**Issue by shunt16** [HYPERNETS/hypernets_processor#85]

**Comment by shunt16** [comment]
Reader checks measurement protocol in config file. This should set a value in the context (context.set_value("standard", False)), which can be checked elsewhere in the processing.

**Comment by clemgoyens** [comment]
Process up to L2A without looking at min. number of scans for ad hoc processing (only?) 
Only standard goes to database! 
E.g. if user want to have L1A_IRR , special request

**Comment by clemgoyens** [comment]
Standard sequence: L1B and L2A for land and L1C and L2A for water
-> Add several levels of users to access other data levels: to be discussed?
